DROP TABLE IF EXISTS ACTIVIDADES;
DROP TABLE IF EXISTS EVENTOS;
DROP TABLE IF EXISTS LUGARES;

CREATE TABLE IF NOT EXISTS ACTIVIDADES (
    ID_ACTIVAD INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL,
    FECHA DATE NOT NULL,
    LUGAR TEXT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    IMAGEN TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENTOS (
    ID_EVENTOS INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    IMAGEN TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS LUGARES(
    ID_LUGARES INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL,
    LUGAR TEXT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    IMAGEN TEXT NOT NULL
);